version: "3.9"

services:
  whisper-backend-transformers:
    build:
      context: ../..
      dockerfile: backends/whisper-transformers/Dockerfile
    env_file:
      - ../../.env
    environment:
      WHISPER_MODEL_WEIGHTS_PATH: ${WHISPER_MODEL_WEIGHTS_PATH:-}
      WHISPER_MODEL_NAME: ${WHISPER_MODEL_NAME:-}
    volumes:
      - type: bind
        source: ${LOCAL_WHISPER_WEIGHTS_DIR:-./weights}
        target: /app/weights
    ports:
      - "${WHISPER_BACKEND_PORT:-7000}:${WHISPER_BACKEND_PORT:-7000}"
    restart: unless-stopped
